from __future__ import annotations

import os

MARKET_DATA_STREAM = "hb.market_data.v1"
MARKET_QUOTE_STREAM = "hb.market_quote.v1"
MARKET_TRADE_STREAM = "hb.market_trade.v1"
MARKET_DEPTH_STREAM = "hb.market_depth.v1"
SIGNAL_STREAM = "hb.signal.v1"
ML_SIGNAL_STREAM = "hb.ml_signal.v1"
RISK_DECISION_STREAM = "hb.risk_decision.v1"
EXECUTION_INTENT_STREAM = "hb.execution_intent.v1"
AUDIT_STREAM = "hb.audit.v1"
DEAD_LETTER_STREAM = "hb.dead_letter.v1"
BOT_TELEMETRY_STREAM = "hb.bot_telemetry.v1"
PORTFOLIO_RISK_STREAM = "hb.portfolio_risk.v1"
PAPER_EXCHANGE_COMMAND_STREAM = "hb.paper_exchange.command.v1"
PAPER_EXCHANGE_EVENT_STREAM = "hb.paper_exchange.event.v1"
PAPER_EXCHANGE_HEARTBEAT_STREAM = "hb.paper_exchange.heartbeat.v1"
ML_FEATURES_STREAM = "hb.ml_features.v1"
DATA_CATALOG_STREAM = "hb.data_catalog.v1"


def _int_env(name: str, default: int) -> int:
    try:
        return max(1, int(os.getenv(name, str(default))))
    except Exception:
        return default


STREAM_RETENTION_MAXLEN = {
    MARKET_DATA_STREAM: _int_env("HB_STREAM_MAXLEN_MARKET_DATA", 50_000),
    MARKET_QUOTE_STREAM: _int_env("HB_STREAM_MAXLEN_MARKET_QUOTE", 100_000),
    MARKET_TRADE_STREAM: _int_env("HB_STREAM_MAXLEN_MARKET_TRADE", 500_000),
    MARKET_DEPTH_STREAM: _int_env("HB_STREAM_MAXLEN_MARKET_DEPTH", 50_000),
    SIGNAL_STREAM: _int_env("HB_STREAM_MAXLEN_SIGNAL", 50_000),
    ML_SIGNAL_STREAM: _int_env("HB_STREAM_MAXLEN_ML_SIGNAL", 50_000),
    RISK_DECISION_STREAM: _int_env("HB_STREAM_MAXLEN_RISK_DECISION", 50_000),
    EXECUTION_INTENT_STREAM: _int_env("HB_STREAM_MAXLEN_EXECUTION_INTENT", 50_000),
    AUDIT_STREAM: _int_env("HB_STREAM_MAXLEN_AUDIT", 100_000),
    DEAD_LETTER_STREAM: _int_env("HB_STREAM_MAXLEN_DEAD_LETTER", 100_000),
    BOT_TELEMETRY_STREAM: _int_env("HB_STREAM_MAXLEN_BOT_TELEMETRY", 50_000),
    PORTFOLIO_RISK_STREAM: _int_env("HB_STREAM_MAXLEN_PORTFOLIO_RISK", 10_000),
    PAPER_EXCHANGE_COMMAND_STREAM: _int_env("HB_STREAM_MAXLEN_PAPER_EXCHANGE_COMMAND", 50_000),
    PAPER_EXCHANGE_EVENT_STREAM: _int_env("HB_STREAM_MAXLEN_PAPER_EXCHANGE_EVENT", 250_000),
    PAPER_EXCHANGE_HEARTBEAT_STREAM: _int_env("HB_STREAM_MAXLEN_PAPER_EXCHANGE_HEARTBEAT", 10_000),
    ML_FEATURES_STREAM: _int_env("HB_STREAM_MAXLEN_ML_FEATURES", 50_000),
    DATA_CATALOG_STREAM: _int_env("HB_STREAM_MAXLEN_DATA_CATALOG", 1_000),
}

DEFAULT_CONSUMER_GROUP = "hb_group_v1"

